name: Playwright tests via Docker

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{secrets.BASE_URL}}
      HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
      HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
      USER_EMAIL: ${{secrets.USER_EMAIL}}
      USER_PASSWORD: ${{secrets.USER_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false # Set to true if you want to push the image to a container registry
          tags: your-image-tag:latest

      - name: Run tests
        run: |
          docker run \
            -e BASE_URL=${BASE_URL} \
            -e HTTP_CREDENTIALS_USERNAME=${HTTP_CREDENTIALS_USERNAME} \
            -e HTTP_CREDENTIALS_PASSWORD=${HTTP_CREDENTIALS_PASSWORD} \
            -e USER_EMAIL=${USER_EMAIL} \
            -e USER_PASSWORD=${USER_PASSWORD} \
            your-image-tag:latest